export const enum BOOK_KEEPER_TYPE {
  ACCOUNT_NFT_BOOK_KEEPER = 1,
  DIRECT_INPUT_BOOK_KEEPER = 2,
  SIMPLE_BOOK_KEEPER =3,
}

export const enum GATE_KEEPER_TYPE {
  WHITELIST_GATE_KEEPER = 1,
  NFT_GATE_KEEPER = 2,
}
